### ISSUE TITLE
change title font-size variable value

### ISSUE THREAD

**Issue by DevLoggith** [commIT-Group/Advice-generator-app#26]
https://github.com/commIT-Group/Advice-generator-app/blob/f222776422c2250b2241159af73387a0844ed203/style.css#L54
`--fs-title:` and `--fs-quote` are both set at the same font size right now. According to the style guide, the quote font size needs to be 28px (or equivalent) and the title font size isn't specified, but needs to be smaller

**Comment by nikkehtine** [comment]
My suggestion is to set the `html` font size according to the style guide:

```css
html {
  font-size: 28px;
}
```

and then use `rem` for everything else, like, for example,

```css
h1 {
  font-size: 0.7rem;
}
```
